---
########## Ubuntu/Debian

- name: Update package index.
  apt:
    name: "*"
    state: latest
  when: ansible_facts.os_family == "Debian" or ansible_distribution == 'Ubuntu'

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist
  when: ansible_facts.os_family == "Debian" or ansible_distribution == 'Ubuntu'

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes
  when: ansible_facts.os_family == "Debian" or ansible_distribution == 'Ubuntu'

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
  when: ansible_facts.os_family == "Debian" or ansible_distribution == 'Ubuntu'

########## Centos/RHEL

- name: Update package index. 
  dnf: 
    name: "*"
    state: latest
  when: ansible_facts.os_family == "RedHat"
