---
- name: Remove older versions of docker
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_facts.os_family == "Debian" or ansible_distribution == "Ubuntu"

##### Set up the Repository

- name: Update package index.
  apt:
    name: "*"
    state: latest
  when: ansible_facts.os_family == "Debian" or ansible_distribution == "Ubuntu"

- name: Install required system packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - 
    state: latest
  when: ansible_facts.os_family == "Debian" or ansible_distribution == "Ubuntu"

##### Add Docker's Official GPG Key

- name: Add signing key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

##### Set up the repository

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} edge"
    state: present
    filename: docker
    update_cache: yes

##### Install Docker

- name: Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Enable the Docker service
  service:
    name: docker
    enabled: yes

- name: Start the Docker service
  service:
    name: docker
    state: started

##### Post Installation

- name: Ensure the docker group is present
  group:
    name: docker
    state: present

- name: Append docker group to the ansible user
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
